name: 1.slacknoti
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every minute

jobs:
  slacknoti:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: '{"text": "Hello, this is a scheduled notification from GitHub Actions!"}' 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: '#khktest'
          SLACK_USERNAME: 'GitHub Actions Bot'
          SLACK_ICON_EMOJI: ':octocat:'
          
      - name: checkout
        uses: actions/checkout@v3
      - name: 파일 생성
        run: |
          echo "test 파일..." > testfile.txt
      - name: 생성 파일 업로드
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./
          commit_message: "신규 파일 추가"
