name: 1.slacknoti
on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  push:
    branches:
      - main

jobs:
  slacknoti:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: '#khktest'
          SLACK_USERNAME: 'GitHub Actions Bot'
          SLACK_ICON_EMOJI: ':octocat:'
          SLACK_MESSAGE: '테스트 노티'
          
      - name: checkout
        uses: actions/checkout@v3
      - name: 파일 생성
        run: |
          echo "test 파일..." > testfile1.txt
      - name: 다른 방법으로 업로드
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: ./testfile1.txt

#      - name: 생성 파일 업로드
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#          github_token: ${{ secrets.GIT_TOKEN }}
#          publish_dir: ./
#          commit_message: "신규 파일 추가"
